// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

/*
Package clusterpb is a generated protocol buffer package.

It is generated from these files:
	cluster.proto

It has these top-level messages:
	MemberInfo
	RegisterRequest
	RegisterResponse
	RequestMessage
	NotifyMessage
	ResponseMessage
	PushMessage
	MemberHandleResponse
	NewMemberRequest
	NewMemberResponse
	SessionClosedRequest
	SessionClosedResponse
	CloseSessionRequest
	CloseSessionResponse
*/
package clusterpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MemberInfo struct {
	Label       string   `protobuf:"bytes,1,opt,name=label" json:"label"`
	ServiceAddr string   `protobuf:"bytes,2,opt,name=serviceAddr" json:"serviceAddr"`
	Services    []string `protobuf:"bytes,3,rep,name=services" json:"services"`
}

func (m *MemberInfo) Reset()                    { *m = MemberInfo{} }
func (m *MemberInfo) String() string            { return proto.CompactTextString(m) }
func (*MemberInfo) ProtoMessage()               {}
func (*MemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MemberInfo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *MemberInfo) GetServiceAddr() string {
	if m != nil {
		return m.ServiceAddr
	}
	return ""
}

func (m *MemberInfo) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

type RegisterRequest struct {
	MemberInfo *MemberInfo `protobuf:"bytes,1,opt,name=memberInfo" json:"memberInfo"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRequest) GetMemberInfo() *MemberInfo {
	if m != nil {
		return m.MemberInfo
	}
	return nil
}

type RegisterResponse struct {
	Members []*MemberInfo `protobuf:"bytes,1,rep,name=members" json:"members"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterResponse) GetMembers() []*MemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type RequestMessage struct {
	ServiceAddr string `protobuf:"bytes,1,opt,name=serviceAddr" json:"serviceAddr"`
	SessionId   int64  `protobuf:"varint,2,opt,name=sessionId" json:"sessionId"`
	Id          uint64 `protobuf:"varint,3,opt,name=id" json:"id"`
	Route       string `protobuf:"bytes,4,opt,name=route" json:"route"`
	Data        []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
}

func (m *RequestMessage) Reset()                    { *m = RequestMessage{} }
func (m *RequestMessage) String() string            { return proto.CompactTextString(m) }
func (*RequestMessage) ProtoMessage()               {}
func (*RequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestMessage) GetServiceAddr() string {
	if m != nil {
		return m.ServiceAddr
	}
	return ""
}

func (m *RequestMessage) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RequestMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestMessage) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *RequestMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotifyMessage struct {
	ServiceAddr string `protobuf:"bytes,1,opt,name=serviceAddr" json:"serviceAddr"`
	SessionId   int64  `protobuf:"varint,2,opt,name=sessionId" json:"sessionId"`
	Route       string `protobuf:"bytes,3,opt,name=route" json:"route"`
	Data        []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
}

func (m *NotifyMessage) Reset()                    { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string            { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()               {}
func (*NotifyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NotifyMessage) GetServiceAddr() string {
	if m != nil {
		return m.ServiceAddr
	}
	return ""
}

func (m *NotifyMessage) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *NotifyMessage) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *NotifyMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseMessage struct {
	SessionId int64  `protobuf:"varint,1,opt,name=sessionId" json:"sessionId"`
	Id        uint64 `protobuf:"varint,2,opt,name=id" json:"id"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (m *ResponseMessage) Reset()                    { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()               {}
func (*ResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResponseMessage) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ResponseMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushMessage struct {
	SessionId int64  `protobuf:"varint,1,opt,name=sessionId" json:"sessionId"`
	Route     string `protobuf:"bytes,2,opt,name=route" json:"route"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (m *PushMessage) Reset()                    { *m = PushMessage{} }
func (m *PushMessage) String() string            { return proto.CompactTextString(m) }
func (*PushMessage) ProtoMessage()               {}
func (*PushMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PushMessage) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PushMessage) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *PushMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MemberHandleResponse struct {
}

func (m *MemberHandleResponse) Reset()                    { *m = MemberHandleResponse{} }
func (m *MemberHandleResponse) String() string            { return proto.CompactTextString(m) }
func (*MemberHandleResponse) ProtoMessage()               {}
func (*MemberHandleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type NewMemberRequest struct {
	MemberInfo *MemberInfo `protobuf:"bytes,1,opt,name=memberInfo" json:"memberInfo"`
}

func (m *NewMemberRequest) Reset()                    { *m = NewMemberRequest{} }
func (m *NewMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*NewMemberRequest) ProtoMessage()               {}
func (*NewMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NewMemberRequest) GetMemberInfo() *MemberInfo {
	if m != nil {
		return m.MemberInfo
	}
	return nil
}

type NewMemberResponse struct {
}

func (m *NewMemberResponse) Reset()                    { *m = NewMemberResponse{} }
func (m *NewMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*NewMemberResponse) ProtoMessage()               {}
func (*NewMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SessionClosedRequest struct {
	SessionId int64 `protobuf:"varint,1,opt,name=sessionId" json:"sessionId"`
}

func (m *SessionClosedRequest) Reset()                    { *m = SessionClosedRequest{} }
func (m *SessionClosedRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionClosedRequest) ProtoMessage()               {}
func (*SessionClosedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SessionClosedRequest) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type SessionClosedResponse struct {
}

func (m *SessionClosedResponse) Reset()                    { *m = SessionClosedResponse{} }
func (m *SessionClosedResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionClosedResponse) ProtoMessage()               {}
func (*SessionClosedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type CloseSessionRequest struct {
	SessionId int64 `protobuf:"varint,1,opt,name=sessionId" json:"sessionId"`
}

func (m *CloseSessionRequest) Reset()                    { *m = CloseSessionRequest{} }
func (m *CloseSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionRequest) ProtoMessage()               {}
func (*CloseSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CloseSessionRequest) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type CloseSessionResponse struct {
}

func (m *CloseSessionResponse) Reset()                    { *m = CloseSessionResponse{} }
func (m *CloseSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionResponse) ProtoMessage()               {}
func (*CloseSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto.RegisterType((*MemberInfo)(nil), "clusterpb.MemberInfo")
	proto.RegisterType((*RegisterRequest)(nil), "clusterpb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "clusterpb.RegisterResponse")
	proto.RegisterType((*RequestMessage)(nil), "clusterpb.RequestMessage")
	proto.RegisterType((*NotifyMessage)(nil), "clusterpb.NotifyMessage")
	proto.RegisterType((*ResponseMessage)(nil), "clusterpb.ResponseMessage")
	proto.RegisterType((*PushMessage)(nil), "clusterpb.PushMessage")
	proto.RegisterType((*MemberHandleResponse)(nil), "clusterpb.MemberHandleResponse")
	proto.RegisterType((*NewMemberRequest)(nil), "clusterpb.NewMemberRequest")
	proto.RegisterType((*NewMemberResponse)(nil), "clusterpb.NewMemberResponse")
	proto.RegisterType((*SessionClosedRequest)(nil), "clusterpb.SessionClosedRequest")
	proto.RegisterType((*SessionClosedResponse)(nil), "clusterpb.SessionClosedResponse")
	proto.RegisterType((*CloseSessionRequest)(nil), "clusterpb.CloseSessionRequest")
	proto.RegisterType((*CloseSessionResponse)(nil), "clusterpb.CloseSessionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Master service

type MasterClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Master/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Master service

type MasterServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Master/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clusterpb.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Master_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

// Client API for Member service

type MemberClient interface {
	HandleRequest(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error)
	HandleNotify(ctx context.Context, in *NotifyMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error)
	HandlePush(ctx context.Context, in *PushMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error)
	HandleResponse(ctx context.Context, in *ResponseMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error)
	NewMember(ctx context.Context, in *NewMemberRequest, opts ...grpc.CallOption) (*NewMemberResponse, error)
	SessionClosed(ctx context.Context, in *SessionClosedRequest, opts ...grpc.CallOption) (*SessionClosedResponse, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
}

type memberClient struct {
	cc *grpc.ClientConn
}

func NewMemberClient(cc *grpc.ClientConn) MemberClient {
	return &memberClient{cc}
}

func (c *memberClient) HandleRequest(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error) {
	out := new(MemberHandleResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Member/HandleRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) HandleNotify(ctx context.Context, in *NotifyMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error) {
	out := new(MemberHandleResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Member/HandleNotify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) HandlePush(ctx context.Context, in *PushMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error) {
	out := new(MemberHandleResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Member/HandlePush", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) HandleResponse(ctx context.Context, in *ResponseMessage, opts ...grpc.CallOption) (*MemberHandleResponse, error) {
	out := new(MemberHandleResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Member/HandleResponse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) NewMember(ctx context.Context, in *NewMemberRequest, opts ...grpc.CallOption) (*NewMemberResponse, error) {
	out := new(NewMemberResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Member/NewMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) SessionClosed(ctx context.Context, in *SessionClosedRequest, opts ...grpc.CallOption) (*SessionClosedResponse, error) {
	out := new(SessionClosedResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Member/SessionClosed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	out := new(CloseSessionResponse)
	err := grpc.Invoke(ctx, "/clusterpb.Member/CloseSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Member service

type MemberServer interface {
	HandleRequest(context.Context, *RequestMessage) (*MemberHandleResponse, error)
	HandleNotify(context.Context, *NotifyMessage) (*MemberHandleResponse, error)
	HandlePush(context.Context, *PushMessage) (*MemberHandleResponse, error)
	HandleResponse(context.Context, *ResponseMessage) (*MemberHandleResponse, error)
	NewMember(context.Context, *NewMemberRequest) (*NewMemberResponse, error)
	SessionClosed(context.Context, *SessionClosedRequest) (*SessionClosedResponse, error)
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
}

func RegisterMemberServer(s *grpc.Server, srv MemberServer) {
	s.RegisterService(&_Member_serviceDesc, srv)
}

func _Member_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Member/HandleRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).HandleRequest(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_HandleNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).HandleNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Member/HandleNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).HandleNotify(ctx, req.(*NotifyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_HandlePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).HandlePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Member/HandlePush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).HandlePush(ctx, req.(*PushMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_HandleResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResponseMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).HandleResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Member/HandleResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).HandleResponse(ctx, req.(*ResponseMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_NewMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).NewMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Member/NewMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).NewMember(ctx, req.(*NewMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_SessionClosed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionClosedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).SessionClosed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Member/SessionClosed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).SessionClosed(ctx, req.(*SessionClosedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusterpb.Member/CloseSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Member_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clusterpb.Member",
	HandlerType: (*MemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleRequest",
			Handler:    _Member_HandleRequest_Handler,
		},
		{
			MethodName: "HandleNotify",
			Handler:    _Member_HandleNotify_Handler,
		},
		{
			MethodName: "HandlePush",
			Handler:    _Member_HandlePush_Handler,
		},
		{
			MethodName: "HandleResponse",
			Handler:    _Member_HandleResponse_Handler,
		},
		{
			MethodName: "NewMember",
			Handler:    _Member_NewMember_Handler,
		},
		{
			MethodName: "SessionClosed",
			Handler:    _Member_SessionClosed_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _Member_CloseSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x2f, 0x0d, 0xf5, 0xc9, 0x85, 0x32, 0x4d, 0x83, 0x31, 0x15, 0x58, 0x7e, 0xca, 0x53,
	0x90, 0x52, 0xf8, 0x00, 0x54, 0x21, 0x12, 0xa1, 0xb4, 0xe0, 0xc2, 0x3b, 0x4e, 0xbd, 0x2d, 0x96,
	0xdc, 0x38, 0x78, 0x1d, 0x50, 0x7f, 0x81, 0xbf, 0xe1, 0x0f, 0x91, 0xbd, 0xb6, 0xb3, 0x76, 0x1d,
	0x64, 0x09, 0xde, 0x3c, 0x33, 0x3b, 0x67, 0xce, 0x99, 0x3d, 0x2b, 0x63, 0x70, 0x1d, 0x6e, 0x79,
	0xc2, 0xe2, 0xe9, 0x26, 0x8e, 0x92, 0x88, 0x8c, 0x3c, 0xdc, 0xac, 0x9c, 0xaf, 0xc0, 0x92, 0xdd,
	0xad, 0x58, 0xbc, 0x58, 0xdf, 0x44, 0x34, 0xc2, 0x41, 0xe8, 0xad, 0x58, 0x68, 0x2a, 0xb6, 0x32,
	0x31, 0x5c, 0x11, 0x90, 0x8d, 0x1e, 0x67, 0xf1, 0x8f, 0xe0, 0x9a, 0xbd, 0xf5, 0xfd, 0xd8, 0x54,
	0xb3, 0x9a, 0x9c, 0x22, 0x0b, 0x87, 0x79, 0xc8, 0x4d, 0xcd, 0xd6, 0x26, 0x86, 0x5b, 0xc6, 0xce,
	0x1c, 0x8f, 0x5d, 0x76, 0x1b, 0xa4, 0xf3, 0x5c, 0xf6, 0x7d, 0xcb, 0x78, 0x42, 0x6f, 0x80, 0xbb,
	0x72, 0x68, 0x36, 0xab, 0x37, 0x3b, 0x99, 0x96, 0xa4, 0xa6, 0x3b, 0x46, 0xae, 0x74, 0xd0, 0x39,
	0xc7, 0xd1, 0x0e, 0x89, 0x6f, 0xa2, 0x35, 0x67, 0xf4, 0x0a, 0x8f, 0xc4, 0x09, 0x6e, 0x2a, 0xb6,
	0xb6, 0x1f, 0xa7, 0x38, 0xe5, 0xfc, 0x52, 0x30, 0xcc, 0x79, 0x2c, 0x19, 0xe7, 0xde, 0x2d, 0xab,
	0xeb, 0x53, 0x1e, 0xea, 0x3b, 0x85, 0xc1, 0x19, 0xe7, 0x41, 0xb4, 0x5e, 0xf8, 0x99, 0x7e, 0xcd,
	0xdd, 0x25, 0x68, 0x08, 0x35, 0xf0, 0x4d, 0xcd, 0x56, 0x26, 0xba, 0xab, 0x06, 0x7e, 0xba, 0xc5,
	0x38, 0xda, 0x26, 0xcc, 0xd4, 0xc5, 0x16, 0xb3, 0x80, 0x08, 0xba, 0xef, 0x25, 0x9e, 0x79, 0x60,
	0x2b, 0x93, 0xbe, 0x9b, 0x7d, 0x3b, 0xf7, 0x18, 0x5c, 0x44, 0x49, 0x70, 0x73, 0xff, 0xbf, 0xa8,
	0x94, 0xa3, 0xb5, 0xa6, 0xd1, 0xba, 0x34, 0xfa, 0x2a, 0xbd, 0x16, 0xb1, 0xc4, 0x62, 0x78, 0x05,
	0x5a, 0x69, 0x56, 0xa9, 0x96, 0x2a, 0x0b, 0x50, 0x4d, 0x02, 0xfd, 0x82, 0xde, 0xc7, 0x2d, 0xff,
	0xd6, 0x0e, 0xb0, 0xe4, 0xaa, 0x36, 0x71, 0x95, 0x61, 0xc7, 0x18, 0x89, 0xab, 0x9c, 0x7b, 0x6b,
	0x3f, 0x64, 0x05, 0x6f, 0x67, 0x81, 0xa3, 0x0b, 0xf6, 0x53, 0x94, 0xfe, 0xd1, 0x5b, 0xc7, 0x78,
	0x22, 0x41, 0xe5, 0xf8, 0xaf, 0x31, 0xba, 0x12, 0x74, 0xcf, 0xc3, 0x88, 0x33, 0xbf, 0x98, 0xf1,
	0x57, 0x5d, 0xce, 0x53, 0x9c, 0xd4, 0xba, 0x72, 0xb8, 0x33, 0x1c, 0x67, 0x99, 0xbc, 0xda, 0x0e,
	0x6d, 0x8c, 0x51, 0xb5, 0x49, 0x80, 0xcd, 0x2e, 0xd1, 0x5d, 0x7a, 0xa9, 0x26, 0x7a, 0x87, 0xc3,
	0xe2, 0x59, 0x90, 0x25, 0x29, 0xad, 0xbd, 0x3a, 0xeb, 0x79, 0x63, 0x2d, 0xe7, 0xd6, 0x99, 0xfd,
	0xd6, 0xd1, 0x15, 0xfa, 0x69, 0x89, 0x41, 0xb1, 0x69, 0x41, 0xf1, 0x59, 0xa5, 0x55, 0x7e, 0x3c,
	0xd6, 0xcb, 0x07, 0xbb, 0xad, 0x5d, 0x52, 0x87, 0x3e, 0xa0, 0x2f, 0x72, 0xc2, 0xeb, 0x64, 0x4a,
	0x2d, 0x15, 0xfb, 0xb7, 0x01, 0x7b, 0x0f, 0x88, 0x5c, 0x6a, 0x34, 0x1a, 0x4b, 0x0d, 0x92, 0xf3,
	0xda, 0x00, 0x5d, 0x62, 0x58, 0xcd, 0xd5, 0x96, 0x57, 0x79, 0x1b, 0x6d, 0x00, 0xe7, 0x30, 0x4a,
	0x0b, 0x91, 0xbc, 0xec, 0xba, 0x47, 0xad, 0xd3, 0xe6, 0x62, 0x89, 0xf4, 0x19, 0x83, 0x8a, 0x83,
	0x48, 0x9e, 0xde, 0xe4, 0x48, 0xcb, 0xde, 0x7f, 0xa0, 0x44, 0xfd, 0x84, 0xbe, 0xec, 0x24, 0x7a,
	0x21, 0xf5, 0x34, 0xf8, 0xb2, 0x22, 0xb9, 0xc9, 0x82, 0x4e, 0x67, 0xd5, 0xcd, 0xfe, 0x27, 0x67,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x82, 0x28, 0x6f, 0x0c, 0x60, 0x06, 0x00, 0x00,
}
