// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package errno

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoomNotFound-10000]
	_ = x[RoomPlayerNumEnough-10001]
	_ = x[RoomExist-10002]
	_ = x[RoomJoinFailed-10003]
	_ = x[RoomPlayerNotFound-10004]
}

const _ErrCode_name = "您输入的房间号不存在, 请确认后再次输入您加入的房间已经满人, 请确认房间号后再次确认房间已存在加入房间失败房间找不到该玩家"

var _ErrCode_index = [...]uint8{0, 56, 121, 136, 154, 178}

func (i ErrCode) String() string {
	i -= 10000
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+10000), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
