// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pb/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息ID
type ID int32

const (
	ID_MSG_BEGIN      ID = 0
	ID_MSG_Connect    ID = 1   //连接(客户端发来第一个消息)
	ID_MSG_Heartbeat  ID = 2   //心跳(服务端返回Connect成功之后每隔1秒发送一个心跳包)
	ID_MSG_JoinRoom   ID = 10  // 进入房间
	ID_MSG_CreateRoom ID = 11  // 创建房间
	ID_MSG_RoomInfo   ID = 12  // 房间信息
	ID_MSG_Progress   ID = 20  //进度
	ID_MSG_Ready      ID = 30  //准备
	ID_MSG_Start      ID = 40  //开始
	ID_MSG_Frame      ID = 50  //帧数据
	ID_MSG_Input      ID = 60  //输入
	ID_MSG_Result     ID = 70  //结果
	ID_MSG_Close      ID = 100 //房间关闭
	ID_MSG_END        ID = 255
)

// Enum value maps for ID.
var (
	ID_name = map[int32]string{
		0:   "MSG_BEGIN",
		1:   "MSG_Connect",
		2:   "MSG_Heartbeat",
		10:  "MSG_JoinRoom",
		11:  "MSG_CreateRoom",
		12:  "MSG_RoomInfo",
		20:  "MSG_Progress",
		30:  "MSG_Ready",
		40:  "MSG_Start",
		50:  "MSG_Frame",
		60:  "MSG_Input",
		70:  "MSG_Result",
		100: "MSG_Close",
		255: "MSG_END",
	}
	ID_value = map[string]int32{
		"MSG_BEGIN":      0,
		"MSG_Connect":    1,
		"MSG_Heartbeat":  2,
		"MSG_JoinRoom":   10,
		"MSG_CreateRoom": 11,
		"MSG_RoomInfo":   12,
		"MSG_Progress":   20,
		"MSG_Ready":      30,
		"MSG_Start":      40,
		"MSG_Frame":      50,
		"MSG_Input":      60,
		"MSG_Result":     70,
		"MSG_Close":      100,
		"MSG_END":        255,
	}
)

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_message_proto_enumTypes[0].Descriptor()
}

func (ID) Type() protoreflect.EnumType {
	return &file_pb_message_proto_enumTypes[0]
}

func (x ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ID.Descriptor instead.
func (ID) EnumDescriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{0}
}

// 错误码
type ERRORCODE int32

const (
	ERRORCODE_ERR_Ok        ERRORCODE = 0 //OK
	ERRORCODE_ERR_NoPlayer  ERRORCODE = 1 //没有这个玩家
	ERRORCODE_ERR_NoRoom    ERRORCODE = 2 //没有房间
	ERRORCODE_ERR_RoomState ERRORCODE = 3 //房间状态不正确
	ERRORCODE_ERR_Token     ERRORCODE = 4 //Token验证失败
)

// Enum value maps for ERRORCODE.
var (
	ERRORCODE_name = map[int32]string{
		0: "ERR_Ok",
		1: "ERR_NoPlayer",
		2: "ERR_NoRoom",
		3: "ERR_RoomState",
		4: "ERR_Token",
	}
	ERRORCODE_value = map[string]int32{
		"ERR_Ok":        0,
		"ERR_NoPlayer":  1,
		"ERR_NoRoom":    2,
		"ERR_RoomState": 3,
		"ERR_Token":     4,
	}
)

func (x ERRORCODE) Enum() *ERRORCODE {
	p := new(ERRORCODE)
	*p = x
	return p
}

func (x ERRORCODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERRORCODE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_message_proto_enumTypes[1].Descriptor()
}

func (ERRORCODE) Type() protoreflect.EnumType {
	return &file_pb_message_proto_enumTypes[1]
}

func (x ERRORCODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERRORCODE.Descriptor instead.
func (ERRORCODE) EnumDescriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{1}
}

// 房间类型
type ROOMTYPE int32

const (
	ROOMTYPE_Room_Type_Default ROOMTYPE = 0   // 单机游戏
	ROOMTYPE_Room_Type_One     ROOMTYPE = 1   // 1人游戏
	ROOMTYPE_Room_Type_Two     ROOMTYPE = 2   // 2人游戏
	ROOMTYPE_Room_Type_Four    ROOMTYPE = 4   // 4人游戏
	ROOMTYPE_Room_Type_VS_Two  ROOMTYPE = 102 // 匹配 2人游戏
	ROOMTYPE_Room_Type_VS_Four ROOMTYPE = 104 // 匹配 4人游戏
)

// Enum value maps for ROOMTYPE.
var (
	ROOMTYPE_name = map[int32]string{
		0:   "Room_Type_Default",
		1:   "Room_Type_One",
		2:   "Room_Type_Two",
		4:   "Room_Type_Four",
		102: "Room_Type_VS_Two",
		104: "Room_Type_VS_Four",
	}
	ROOMTYPE_value = map[string]int32{
		"Room_Type_Default": 0,
		"Room_Type_One":     1,
		"Room_Type_Two":     2,
		"Room_Type_Four":    4,
		"Room_Type_VS_Two":  102,
		"Room_Type_VS_Four": 104,
	}
)

func (x ROOMTYPE) Enum() *ROOMTYPE {
	p := new(ROOMTYPE)
	*p = x
	return p
}

func (x ROOMTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ROOMTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_message_proto_enumTypes[2].Descriptor()
}

func (ROOMTYPE) Type() protoreflect.EnumType {
	return &file_pb_message_proto_enumTypes[2]
}

func (x ROOMTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ROOMTYPE.Descriptor instead.
func (ROOMTYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{2}
}

//客户端发来的第一个消息
type C2S_ConnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID *uint64 `protobuf:"varint,1,opt,name=playerID,proto3,oneof" json:"playerID,omitempty"` // 唯一ID
	Token    *string `protobuf:"bytes,10,opt,name=token,proto3,oneof" json:"token,omitempty"`       // 令牌
}

func (x *C2S_ConnectMsg) Reset() {
	*x = C2S_ConnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_ConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ConnectMsg) ProtoMessage() {}

func (x *C2S_ConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ConnectMsg.ProtoReflect.Descriptor instead.
func (*C2S_ConnectMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_ConnectMsg) GetPlayerID() uint64 {
	if x != nil && x.PlayerID != nil {
		return *x.PlayerID
	}
	return 0
}

func (x *C2S_ConnectMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

// 加入房间 -> S2C_JoinRoomMsg
type C2S_JoinRoomMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId *uint64 `protobuf:"varint,1,opt,name=roomId,proto3,oneof" json:"roomId,omitempty"` // 房间号
}

func (x *C2S_JoinRoomMsg) Reset() {
	*x = C2S_JoinRoomMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_JoinRoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_JoinRoomMsg) ProtoMessage() {}

func (x *C2S_JoinRoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_JoinRoomMsg.ProtoReflect.Descriptor instead.
func (*C2S_JoinRoomMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{1}
}

func (x *C2S_JoinRoomMsg) GetRoomId() uint64 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

//服务端返回连接结果
type S2C_ConnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode *ERRORCODE `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERRORCODE,oneof" json:"errorCode,omitempty"` //错误码
}

func (x *S2C_ConnectMsg) Reset() {
	*x = S2C_ConnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_ConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ConnectMsg) ProtoMessage() {}

func (x *S2C_ConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ConnectMsg.ProtoReflect.Descriptor instead.
func (*S2C_ConnectMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_ConnectMsg) GetErrorCode() ERRORCODE {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ERRORCODE_ERR_Ok
}

// 创建房间 -> S2C_JoinRoomMsg
type C2S_CreateRoomMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   *uint64   `protobuf:"varint,1,opt,name=roomId,proto3,oneof" json:"roomId,omitempty"`                      // 房间 id
	RoomType *ROOMTYPE `protobuf:"varint,2,opt,name=roomType,proto3,enum=pb.ROOMTYPE,oneof" json:"roomType,omitempty"` // 房间类型
}

func (x *C2S_CreateRoomMsg) Reset() {
	*x = C2S_CreateRoomMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_CreateRoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CreateRoomMsg) ProtoMessage() {}

func (x *C2S_CreateRoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CreateRoomMsg.ProtoReflect.Descriptor instead.
func (*C2S_CreateRoomMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_CreateRoomMsg) GetRoomId() uint64 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *C2S_CreateRoomMsg) GetRoomType() ROOMTYPE {
	if x != nil && x.RoomType != nil {
		return *x.RoomType
	}
	return ROOMTYPE_Room_Type_Default
}

// 广播📢 - 服务端返回进入房间消息
type S2C_JoinRoomMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomSeatId *int32     `protobuf:"varint,1,opt,name=roomSeatId,proto3,oneof" json:"roomSeatId,omitempty"`                 //自己的位置索引id(1~N)
	Others     []uint64   `protobuf:"varint,2,rep,packed,name=others,proto3" json:"others,omitempty"`                        //其他人的id
	Pros       []int32    `protobuf:"varint,3,rep,packed,name=pros,proto3" json:"pros,omitempty"`                            //其他人的进度
	RandomSeed *int32     `protobuf:"varint,4,opt,name=randomSeed,proto3,oneof" json:"randomSeed,omitempty"`                 //随机种子
	ErrorCode  *ERRORCODE `protobuf:"varint,5,opt,name=errorCode,proto3,enum=pb.ERRORCODE,oneof" json:"errorCode,omitempty"` //错误码
	OwnerId    *uint64    `protobuf:"varint,6,opt,name=ownerId,proto3,oneof" json:"ownerId,omitempty"`                       // 房主
}

func (x *S2C_JoinRoomMsg) Reset() {
	*x = S2C_JoinRoomMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_JoinRoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_JoinRoomMsg) ProtoMessage() {}

func (x *S2C_JoinRoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_JoinRoomMsg.ProtoReflect.Descriptor instead.
func (*S2C_JoinRoomMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_JoinRoomMsg) GetRoomSeatId() int32 {
	if x != nil && x.RoomSeatId != nil {
		return *x.RoomSeatId
	}
	return 0
}

func (x *S2C_JoinRoomMsg) GetOthers() []uint64 {
	if x != nil {
		return x.Others
	}
	return nil
}

func (x *S2C_JoinRoomMsg) GetPros() []int32 {
	if x != nil {
		return x.Pros
	}
	return nil
}

func (x *S2C_JoinRoomMsg) GetRandomSeed() int32 {
	if x != nil && x.RandomSeed != nil {
		return *x.RandomSeed
	}
	return 0
}

func (x *S2C_JoinRoomMsg) GetErrorCode() ERRORCODE {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ERRORCODE_ERR_Ok
}

func (x *S2C_JoinRoomMsg) GetOwnerId() uint64 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

// 广播📢 - 服务端广播房间信息
type S2C_RoomInfoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     *uint64    `protobuf:"varint,1,opt,name=roomId,proto3,oneof" json:"roomId,omitempty"`                         // 房间 id
	OwnerId    *uint64    `protobuf:"varint,2,opt,name=ownerId,proto3,oneof" json:"ownerId,omitempty"`                       // 房主
	Others     []uint64   `protobuf:"varint,3,rep,packed,name=others,proto3" json:"others,omitempty"`                        //其他人的id
	RandomSeed *int32     `protobuf:"varint,4,opt,name=randomSeed,proto3,oneof" json:"randomSeed,omitempty"`                 //随机种子
	ErrorCode  *ERRORCODE `protobuf:"varint,5,opt,name=errorCode,proto3,enum=pb.ERRORCODE,oneof" json:"errorCode,omitempty"` //错误码
}

func (x *S2C_RoomInfoMsg) Reset() {
	*x = S2C_RoomInfoMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomInfoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomInfoMsg) ProtoMessage() {}

func (x *S2C_RoomInfoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomInfoMsg.ProtoReflect.Descriptor instead.
func (*S2C_RoomInfoMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_RoomInfoMsg) GetRoomId() uint64 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *S2C_RoomInfoMsg) GetOwnerId() uint64 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

func (x *S2C_RoomInfoMsg) GetOthers() []uint64 {
	if x != nil {
		return x.Others
	}
	return nil
}

func (x *S2C_RoomInfoMsg) GetRandomSeed() int32 {
	if x != nil && x.RandomSeed != nil {
		return *x.RandomSeed
	}
	return 0
}

func (x *S2C_RoomInfoMsg) GetErrorCode() ERRORCODE {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ERRORCODE_ERR_Ok
}

// 广播📢 - 服务端广播开始游戏消息
type S2C_StartMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *int64 `protobuf:"varint,1,opt,name=timeStamp,proto3,oneof" json:"timeStamp,omitempty"` //同步时间戳
}

func (x *S2C_StartMsg) Reset() {
	*x = S2C_StartMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_StartMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_StartMsg) ProtoMessage() {}

func (x *S2C_StartMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_StartMsg.ProtoReflect.Descriptor instead.
func (*S2C_StartMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_StartMsg) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

// 读条进度
type C2S_ProgressMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pro *int32 `protobuf:"varint,1,opt,name=pro,proto3,oneof" json:"pro,omitempty"` //进度值0~100
}

func (x *C2S_ProgressMsg) Reset() {
	*x = C2S_ProgressMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_ProgressMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ProgressMsg) ProtoMessage() {}

func (x *C2S_ProgressMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ProgressMsg.ProtoReflect.Descriptor instead.
func (*C2S_ProgressMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_ProgressMsg) GetPro() int32 {
	if x != nil && x.Pro != nil {
		return *x.Pro
	}
	return 0
}

// 读条进度
type S2C_ProgressMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  *uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`   //id
	Pro *int32  `protobuf:"varint,2,opt,name=pro,proto3,oneof" json:"pro,omitempty"` //进度值0~100
}

func (x *S2C_ProgressMsg) Reset() {
	*x = S2C_ProgressMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_ProgressMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ProgressMsg) ProtoMessage() {}

func (x *S2C_ProgressMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ProgressMsg.ProtoReflect.Descriptor instead.
func (*S2C_ProgressMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_ProgressMsg) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *S2C_ProgressMsg) GetPro() int32 {
	if x != nil && x.Pro != nil {
		return *x.Pro
	}
	return 0
}

// 操作输入消息
type C2S_InputMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameID *uint32  `protobuf:"varint,4,opt,name=frameID,proto3,oneof" json:"frameID,omitempty"` //帧ID
	Sid     *int32   `protobuf:"varint,1,opt,name=sid,proto3,oneof" json:"sid,omitempty"`         //操作id
	X       *float32 `protobuf:"fixed32,2,opt,name=x,proto3,oneof" json:"x,omitempty"`            //操作位置x
	Y       *float32 `protobuf:"fixed32,3,opt,name=y,proto3,oneof" json:"y,omitempty"`            //操作位置y
	Z       *float32 `protobuf:"fixed32,5,opt,name=z,proto3,oneof" json:"z,omitempty"`
	Ex      *float32 `protobuf:"fixed32,6,opt,name=ex,proto3,oneof" json:"ex,omitempty"`
	Ey      *float32 `protobuf:"fixed32,7,opt,name=ey,proto3,oneof" json:"ey,omitempty"`
	Ez      *float32 `protobuf:"fixed32,8,opt,name=ez,proto3,oneof" json:"ez,omitempty"`
	TurretY *float32 `protobuf:"fixed32,9,opt,name=turretY,proto3,oneof" json:"turretY,omitempty"`
	GunX    *float32 `protobuf:"fixed32,10,opt,name=gunX,proto3,oneof" json:"gunX,omitempty"`
	Hp      *uint64  `protobuf:"varint,12,opt,name=hp,proto3,oneof" json:"hp,omitempty"`         // 血量
	Damage  *uint64  `protobuf:"varint,13,opt,name=damage,proto3,oneof" json:"damage,omitempty"` // 伤害
}

func (x *C2S_InputMsg) Reset() {
	*x = C2S_InputMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_InputMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_InputMsg) ProtoMessage() {}

func (x *C2S_InputMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_InputMsg.ProtoReflect.Descriptor instead.
func (*C2S_InputMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{9}
}

func (x *C2S_InputMsg) GetFrameID() uint32 {
	if x != nil && x.FrameID != nil {
		return *x.FrameID
	}
	return 0
}

func (x *C2S_InputMsg) GetSid() int32 {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return 0
}

func (x *C2S_InputMsg) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *C2S_InputMsg) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *C2S_InputMsg) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *C2S_InputMsg) GetEx() float32 {
	if x != nil && x.Ex != nil {
		return *x.Ex
	}
	return 0
}

func (x *C2S_InputMsg) GetEy() float32 {
	if x != nil && x.Ey != nil {
		return *x.Ey
	}
	return 0
}

func (x *C2S_InputMsg) GetEz() float32 {
	if x != nil && x.Ez != nil {
		return *x.Ez
	}
	return 0
}

func (x *C2S_InputMsg) GetTurretY() float32 {
	if x != nil && x.TurretY != nil {
		return *x.TurretY
	}
	return 0
}

func (x *C2S_InputMsg) GetGunX() float32 {
	if x != nil && x.GunX != nil {
		return *x.GunX
	}
	return 0
}

func (x *C2S_InputMsg) GetHp() uint64 {
	if x != nil && x.Hp != nil {
		return *x.Hp
	}
	return 0
}

func (x *C2S_InputMsg) GetDamage() uint64 {
	if x != nil && x.Damage != nil {
		return *x.Damage
	}
	return 0
}

// 帧存储操作输入
type InputData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid        *int32   `protobuf:"varint,1,opt,name=sid,proto3,oneof" json:"sid,omitempty"` //操作id
	X          *float32 `protobuf:"fixed32,2,opt,name=x,proto3,oneof" json:"x,omitempty"`    //操作位置x
	Y          *float32 `protobuf:"fixed32,3,opt,name=y,proto3,oneof" json:"y,omitempty"`    //操作位置y
	Z          *float32 `protobuf:"fixed32,5,opt,name=z,proto3,oneof" json:"z,omitempty"`
	Ex         *float32 `protobuf:"fixed32,6,opt,name=ex,proto3,oneof" json:"ex,omitempty"`
	Ey         *float32 `protobuf:"fixed32,7,opt,name=ey,proto3,oneof" json:"ey,omitempty"`
	Ez         *float32 `protobuf:"fixed32,8,opt,name=ez,proto3,oneof" json:"ez,omitempty"`
	TurretY    *float32 `protobuf:"fixed32,9,opt,name=turretY,proto3,oneof" json:"turretY,omitempty"`
	GunX       *float32 `protobuf:"fixed32,10,opt,name=gunX,proto3,oneof" json:"gunX,omitempty"`
	Hp         *uint64  `protobuf:"varint,12,opt,name=hp,proto3,oneof" json:"hp,omitempty"`                 // 血量
	Damage     *uint64  `protobuf:"varint,13,opt,name=damage,proto3,oneof" json:"damage,omitempty"`         // 伤害
	PlayerID   *uint64  `protobuf:"varint,21,opt,name=playerID,proto3,oneof" json:"playerID,omitempty"`     // 玩家id
	RoomSeatId *int32   `protobuf:"varint,22,opt,name=roomSeatId,proto3,oneof" json:"roomSeatId,omitempty"` //操作者的位置索引id(1~N)
}

func (x *InputData) Reset() {
	*x = InputData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputData.ProtoReflect.Descriptor instead.
func (*InputData) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{10}
}

func (x *InputData) GetSid() int32 {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return 0
}

func (x *InputData) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *InputData) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *InputData) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *InputData) GetEx() float32 {
	if x != nil && x.Ex != nil {
		return *x.Ex
	}
	return 0
}

func (x *InputData) GetEy() float32 {
	if x != nil && x.Ey != nil {
		return *x.Ey
	}
	return 0
}

func (x *InputData) GetEz() float32 {
	if x != nil && x.Ez != nil {
		return *x.Ez
	}
	return 0
}

func (x *InputData) GetTurretY() float32 {
	if x != nil && x.TurretY != nil {
		return *x.TurretY
	}
	return 0
}

func (x *InputData) GetGunX() float32 {
	if x != nil && x.GunX != nil {
		return *x.GunX
	}
	return 0
}

func (x *InputData) GetHp() uint64 {
	if x != nil && x.Hp != nil {
		return *x.Hp
	}
	return 0
}

func (x *InputData) GetDamage() uint64 {
	if x != nil && x.Damage != nil {
		return *x.Damage
	}
	return 0
}

func (x *InputData) GetPlayerID() uint64 {
	if x != nil && x.PlayerID != nil {
		return *x.PlayerID
	}
	return 0
}

func (x *InputData) GetRoomSeatId() int32 {
	if x != nil && x.RoomSeatId != nil {
		return *x.RoomSeatId
	}
	return 0
}

// 帧数据
type FrameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameID *uint32      `protobuf:"varint,1,opt,name=frameID,proto3,oneof" json:"frameID,omitempty"` // 帧ID
	Input   []*InputData `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`            // 操作输入
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{11}
}

func (x *FrameData) GetFrameID() uint32 {
	if x != nil && x.FrameID != nil {
		return *x.FrameID
	}
	return 0
}

func (x *FrameData) GetInput() []*InputData {
	if x != nil {
		return x.Input
	}
	return nil
}

// 广播📢 - 广播帧消息
type S2C_FrameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frames []*FrameData `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"` // 帧数据
}

func (x *S2C_FrameMsg) Reset() {
	*x = S2C_FrameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_FrameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_FrameMsg) ProtoMessage() {}

func (x *S2C_FrameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_FrameMsg.ProtoReflect.Descriptor instead.
func (*S2C_FrameMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{12}
}

func (x *S2C_FrameMsg) GetFrames() []*FrameData {
	if x != nil {
		return x.Frames
	}
	return nil
}

// 结果消息
type C2S_ResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerID *uint64 `protobuf:"varint,1,opt,name=winnerID,proto3,oneof" json:"winnerID,omitempty"` // 胜利者ID
}

func (x *C2S_ResultMsg) Reset() {
	*x = C2S_ResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_ResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ResultMsg) ProtoMessage() {}

func (x *C2S_ResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ResultMsg.ProtoReflect.Descriptor instead.
func (*C2S_ResultMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{13}
}

func (x *C2S_ResultMsg) GetWinnerID() uint64 {
	if x != nil && x.WinnerID != nil {
		return *x.WinnerID
	}
	return 0
}

// 广播📢 - 结果消息
type S2C_ResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerID *uint64 `protobuf:"varint,1,opt,name=winnerID,proto3,oneof" json:"winnerID,omitempty"` // 胜利者ID
}

func (x *S2C_ResultMsg) Reset() {
	*x = S2C_ResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_ResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ResultMsg) ProtoMessage() {}

func (x *S2C_ResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ResultMsg.ProtoReflect.Descriptor instead.
func (*S2C_ResultMsg) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{14}
}

func (x *S2C_ResultMsg) GetWinnerID() uint64 {
	if x != nil && x.WinnerID != nil {
		return *x.WinnerID
	}
	return 0
}

var File_pb_message_proto protoreflect.FileDescriptor

var file_pb_message_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x63, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x39, 0x0a, 0x0f, 0x43,
	0x32, 0x53, 0x5f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x1b,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x30, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x43, 0x4f, 0x44, 0x45, 0x48, 0x00, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x77, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x5f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x4f, 0x4f, 0x4d, 0x54, 0x59, 0x50, 0x45, 0x48, 0x01, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x90, 0x02, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x23, 0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x61,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x6f, 0x6f,
	0x6d, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x72, 0x6f, 0x73, 0x12, 0x23, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x53, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0a, 0x72, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x43, 0x4f, 0x44, 0x45, 0x48, 0x02, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x03,
	0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x49, 0x64, 0x22, 0xf0, 0x01, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x0a,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x02, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x30, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x43,
	0x4f, 0x44, 0x45, 0x48, 0x03, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3f, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x5f, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x30, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x03, 0x70,
	0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x70, 0x72, 0x6f, 0x88,
	0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x70, 0x72, 0x6f, 0x22, 0x4c, 0x0a, 0x0f, 0x53, 0x32,
	0x43, 0x5f, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x13, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x70, 0x72, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x03, 0x70, 0x72, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x70, 0x72, 0x6f, 0x22, 0x88, 0x03, 0x0a, 0x0c, 0x43, 0x32, 0x53,
	0x5f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x07, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x03, 0x73, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x11, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02, 0x52, 0x01, 0x78, 0x88,
	0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x03, 0x52,
	0x01, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x04, 0x52, 0x01, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65, 0x78, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x05, 0x52, 0x02, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a,
	0x02, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x48, 0x06, 0x52, 0x02, 0x65, 0x79, 0x88,
	0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65, 0x7a, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x48, 0x07,
	0x52, 0x02, 0x65, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x74, 0x75, 0x72, 0x72, 0x65,
	0x74, 0x59, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x48, 0x08, 0x52, 0x07, 0x74, 0x75, 0x72, 0x72,
	0x65, 0x74, 0x59, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x67, 0x75, 0x6e, 0x58, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x09, 0x52, 0x04, 0x67, 0x75, 0x6e, 0x58, 0x88, 0x01, 0x01, 0x12,
	0x13, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x48, 0x0a, 0x52, 0x02, 0x68,
	0x70, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x04, 0x48, 0x0b, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x42, 0x06, 0x0a,
	0x04, 0x5f, 0x73, 0x69, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x78, 0x42, 0x04, 0x0a, 0x02, 0x5f,
	0x79, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x7a, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x78, 0x42, 0x05,
	0x0a, 0x03, 0x5f, 0x65, 0x79, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x7a, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x59, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x67, 0x75, 0x6e,
	0x58, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x68, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x22, 0xbc, 0x03, 0x0a, 0x09, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x15, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x01, 0x78, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02, 0x52, 0x01, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11,
	0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x03, 0x52, 0x01, 0x7a, 0x88, 0x01,
	0x01, 0x12, 0x13, 0x0a, 0x02, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x48, 0x04, 0x52,
	0x02, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x05, 0x52, 0x02, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65,
	0x7a, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x48, 0x06, 0x52, 0x02, 0x65, 0x7a, 0x88, 0x01, 0x01,
	0x12, 0x1d, 0x0a, 0x07, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x59, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x02, 0x48, 0x07, 0x52, 0x07, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x59, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x67, 0x75, 0x6e, 0x58, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x48, 0x08, 0x52,
	0x04, 0x67, 0x75, 0x6e, 0x58, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x04, 0x48, 0x09, 0x52, 0x02, 0x68, 0x70, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a,
	0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x48, 0x0a, 0x52,
	0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x15, 0x20, 0x01, 0x28, 0x04, 0x48, 0x0b, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x72,
	0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x18, 0x16, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x0c, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x73, 0x69, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x78, 0x42, 0x04,
	0x0a, 0x02, 0x5f, 0x79, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x7a, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65,
	0x78, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x79, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x7a, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x59, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x67, 0x75, 0x6e, 0x58, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x68, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x44, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x61, 0x74,
	0x49, 0x64, 0x22, 0x5b, 0x0a, 0x09, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1d, 0x0a, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x00, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x23,
	0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22,
	0x35, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x5f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12,
	0x25, 0x0a, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x77, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x44, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x77, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x49, 0x44, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x77, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x49, 0x44, 0x2a, 0xea, 0x01, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x53, 0x47, 0x5f, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53,
	0x47, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d,
	0x53, 0x47, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0x02, 0x12, 0x10,
	0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x0a,
	0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x10, 0x0b, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x10, 0x0c, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x10, 0x14, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x53, 0x47, 0x5f,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x1e, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x53, 0x47, 0x5f, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x10, 0x28, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x53, 0x47, 0x5f, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x10, 0x32, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x53, 0x47, 0x5f, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x10, 0x3c, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x10, 0x46, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x10, 0x64, 0x12, 0x0c, 0x0a, 0x07, 0x4d, 0x53, 0x47, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0xff,
	0x01, 0x2a, 0x5b, 0x0a, 0x09, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x43, 0x4f, 0x44, 0x45, 0x12, 0x0a,
	0x0a, 0x06, 0x45, 0x52, 0x52, 0x5f, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x52,
	0x52, 0x5f, 0x4e, 0x6f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x45, 0x52, 0x52, 0x5f, 0x4e, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d,
	0x45, 0x52, 0x52, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x10, 0x03, 0x12,
	0x0d, 0x0a, 0x09, 0x45, 0x52, 0x52, 0x5f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x10, 0x04, 0x2a, 0x88,
	0x01, 0x0a, 0x08, 0x52, 0x4f, 0x4f, 0x4d, 0x54, 0x59, 0x50, 0x45, 0x12, 0x15, 0x0a, 0x11, 0x52,
	0x6f, 0x6f, 0x6d, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x4f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x54, 0x77, 0x6f, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x6f, 0x6f, 0x6d,
	0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x46, 0x6f, 0x75, 0x72, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x56, 0x53, 0x5f, 0x54, 0x77, 0x6f,
	0x10, 0x66, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x56, 0x53, 0x5f, 0x46, 0x6f, 0x75, 0x72, 0x10, 0x68, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_message_proto_rawDescOnce sync.Once
	file_pb_message_proto_rawDescData = file_pb_message_proto_rawDesc
)

func file_pb_message_proto_rawDescGZIP() []byte {
	file_pb_message_proto_rawDescOnce.Do(func() {
		file_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_message_proto_rawDescData)
	})
	return file_pb_message_proto_rawDescData
}

var file_pb_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pb_message_proto_goTypes = []interface{}{
	(ID)(0),                   // 0: pb.ID
	(ERRORCODE)(0),            // 1: pb.ERRORCODE
	(ROOMTYPE)(0),             // 2: pb.ROOMTYPE
	(*C2S_ConnectMsg)(nil),    // 3: pb.C2S_ConnectMsg
	(*C2S_JoinRoomMsg)(nil),   // 4: pb.C2S_JoinRoomMsg
	(*S2C_ConnectMsg)(nil),    // 5: pb.S2C_ConnectMsg
	(*C2S_CreateRoomMsg)(nil), // 6: pb.C2S_CreateRoomMsg
	(*S2C_JoinRoomMsg)(nil),   // 7: pb.S2C_JoinRoomMsg
	(*S2C_RoomInfoMsg)(nil),   // 8: pb.S2C_RoomInfoMsg
	(*S2C_StartMsg)(nil),      // 9: pb.S2C_StartMsg
	(*C2S_ProgressMsg)(nil),   // 10: pb.C2S_ProgressMsg
	(*S2C_ProgressMsg)(nil),   // 11: pb.S2C_ProgressMsg
	(*C2S_InputMsg)(nil),      // 12: pb.C2S_InputMsg
	(*InputData)(nil),         // 13: pb.InputData
	(*FrameData)(nil),         // 14: pb.FrameData
	(*S2C_FrameMsg)(nil),      // 15: pb.S2C_FrameMsg
	(*C2S_ResultMsg)(nil),     // 16: pb.C2S_ResultMsg
	(*S2C_ResultMsg)(nil),     // 17: pb.S2C_ResultMsg
}
var file_pb_message_proto_depIdxs = []int32{
	1,  // 0: pb.S2C_ConnectMsg.errorCode:type_name -> pb.ERRORCODE
	2,  // 1: pb.C2S_CreateRoomMsg.roomType:type_name -> pb.ROOMTYPE
	1,  // 2: pb.S2C_JoinRoomMsg.errorCode:type_name -> pb.ERRORCODE
	1,  // 3: pb.S2C_RoomInfoMsg.errorCode:type_name -> pb.ERRORCODE
	13, // 4: pb.FrameData.input:type_name -> pb.InputData
	14, // 5: pb.S2C_FrameMsg.frames:type_name -> pb.FrameData
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pb_message_proto_init() }
func file_pb_message_proto_init() {
	if File_pb_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_ConnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_JoinRoomMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_ConnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_CreateRoomMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_JoinRoomMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_RoomInfoMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_StartMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_ProgressMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_ProgressMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_InputMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_FrameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_ResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_ResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_message_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_pb_message_proto_msgTypes[14].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_message_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_message_proto_goTypes,
		DependencyIndexes: file_pb_message_proto_depIdxs,
		EnumInfos:         file_pb_message_proto_enumTypes,
		MessageInfos:      file_pb_message_proto_msgTypes,
	}.Build()
	File_pb_message_proto = out.File
	file_pb_message_proto_rawDesc = nil
	file_pb_message_proto_goTypes = nil
	file_pb_message_proto_depIdxs = nil
}
