// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: tank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义
// 错误信息
type ErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorInfo) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     uint64      `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomMaster int64       `protobuf:"varint,4,opt,name=roomMaster,proto3" json:"roomMaster,omitempty"`
	RandomSeed int64       `protobuf:"varint,2,opt,name=randomSeed,proto3" json:"randomSeed,omitempty"` //随机种子
	Players    []*UserInfo `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`        //其他人的id
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{2}
}

func (x *RoomInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetRoomMaster() int64 {
	if x != nil {
		return x.RoomMaster
	}
	return 0
}

func (x *RoomInfo) GetRandomSeed() int64 {
	if x != nil {
		return x.RandomSeed
	}
	return 0
}

func (x *RoomInfo) GetPlayers() []*UserInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// request
// 创建房间
type Login_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Login_Request) Reset() {
	*x = Login_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Request) ProtoMessage() {}

func (x *Login_Request) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Request.ProtoReflect.Descriptor instead.
func (*Login_Request) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{3}
}

func (x *Login_Request) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Login_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Login_Response) Reset() {
	*x = Login_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Response) ProtoMessage() {}

func (x *Login_Response) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Response.ProtoReflect.Descriptor instead.
func (*Login_Response) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{4}
}

func (x *Login_Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// 创建房间
type CreateRoom_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId         uint64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MaxPlayerCount uint32 `protobuf:"varint,2,opt,name=maxPlayerCount,proto3" json:"maxPlayerCount,omitempty"`
}

func (x *CreateRoom_Request) Reset() {
	*x = CreateRoom_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoom_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom_Request) ProtoMessage() {}

func (x *CreateRoom_Request) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom_Request.ProtoReflect.Descriptor instead.
func (*CreateRoom_Request) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoom_Request) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoom_Request) GetMaxPlayerCount() uint32 {
	if x != nil {
		return x.MaxPlayerCount
	}
	return 0
}

type CreateRoom_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *RoomInfo  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *CreateRoom_Response) Reset() {
	*x = CreateRoom_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoom_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom_Response) ProtoMessage() {}

func (x *CreateRoom_Response) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom_Response.ProtoReflect.Descriptor instead.
func (*CreateRoom_Response) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoom_Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateRoom_Response) GetData() *RoomInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 加入房间
type JoinRoom_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId uint64 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *JoinRoom_Request) Reset() {
	*x = JoinRoom_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoom_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom_Request) ProtoMessage() {}

func (x *JoinRoom_Request) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom_Request.ProtoReflect.Descriptor instead.
func (*JoinRoom_Request) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRoom_Request) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *JoinRoom_Request) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type JoinRoom_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *RoomInfo  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *JoinRoom_Response) Reset() {
	*x = JoinRoom_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoom_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom_Response) ProtoMessage() {}

func (x *JoinRoom_Response) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom_Response.ProtoReflect.Descriptor instead.
func (*JoinRoom_Response) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoom_Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JoinRoom_Response) GetData() *RoomInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 退出房间
type LeaveRoom_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *LeaveRoom_Request) Reset() {
	*x = LeaveRoom_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoom_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom_Request) ProtoMessage() {}

func (x *LeaveRoom_Request) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom_Request.ProtoReflect.Descriptor instead.
func (*LeaveRoom_Request) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveRoom_Request) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LeaveRoom_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LeaveRoom_Response) Reset() {
	*x = LeaveRoom_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoom_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom_Response) ProtoMessage() {}

func (x *LeaveRoom_Response) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom_Response.ProtoReflect.Descriptor instead.
func (*LeaveRoom_Response) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveRoom_Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// 上传操作输入指令
type Input_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameID *uint32  `protobuf:"varint,4,opt,name=frameID,proto3,oneof" json:"frameID,omitempty"` //帧ID
	Sid     *uint32  `protobuf:"varint,1,opt,name=sid,proto3,oneof" json:"sid,omitempty"`         //操作id
	X       *float32 `protobuf:"fixed32,2,opt,name=x,proto3,oneof" json:"x,omitempty"`            //操作位置x
	Y       *float32 `protobuf:"fixed32,3,opt,name=y,proto3,oneof" json:"y,omitempty"`            //操作位置y
	Z       *float32 `protobuf:"fixed32,5,opt,name=z,proto3,oneof" json:"z,omitempty"`
	Ex      *float32 `protobuf:"fixed32,6,opt,name=ex,proto3,oneof" json:"ex,omitempty"`
	Ey      *float32 `protobuf:"fixed32,7,opt,name=ey,proto3,oneof" json:"ey,omitempty"`
	Ez      *float32 `protobuf:"fixed32,8,opt,name=ez,proto3,oneof" json:"ez,omitempty"`
	TurretY *float32 `protobuf:"fixed32,9,opt,name=turretY,proto3,oneof" json:"turretY,omitempty"`
	GunX    *float32 `protobuf:"fixed32,10,opt,name=gunX,proto3,oneof" json:"gunX,omitempty"`
	Hp      *uint64  `protobuf:"varint,12,opt,name=hp,proto3,oneof" json:"hp,omitempty"`         // 血量
	Damage  *uint64  `protobuf:"varint,13,opt,name=damage,proto3,oneof" json:"damage,omitempty"` // 伤害
}

func (x *Input_Notify) Reset() {
	*x = Input_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input_Notify) ProtoMessage() {}

func (x *Input_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input_Notify.ProtoReflect.Descriptor instead.
func (*Input_Notify) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{11}
}

func (x *Input_Notify) GetFrameID() uint32 {
	if x != nil && x.FrameID != nil {
		return *x.FrameID
	}
	return 0
}

func (x *Input_Notify) GetSid() uint32 {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return 0
}

func (x *Input_Notify) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Input_Notify) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Input_Notify) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *Input_Notify) GetEx() float32 {
	if x != nil && x.Ex != nil {
		return *x.Ex
	}
	return 0
}

func (x *Input_Notify) GetEy() float32 {
	if x != nil && x.Ey != nil {
		return *x.Ey
	}
	return 0
}

func (x *Input_Notify) GetEz() float32 {
	if x != nil && x.Ez != nil {
		return *x.Ez
	}
	return 0
}

func (x *Input_Notify) GetTurretY() float32 {
	if x != nil && x.TurretY != nil {
		return *x.TurretY
	}
	return 0
}

func (x *Input_Notify) GetGunX() float32 {
	if x != nil && x.GunX != nil {
		return *x.GunX
	}
	return 0
}

func (x *Input_Notify) GetHp() uint64 {
	if x != nil && x.Hp != nil {
		return *x.Hp
	}
	return 0
}

func (x *Input_Notify) GetDamage() uint64 {
	if x != nil && x.Damage != nil {
		return *x.Damage
	}
	return 0
}

// 结果消息
type Result_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerID uint64 `protobuf:"varint,1,opt,name=winnerID,proto3" json:"winnerID,omitempty"` // 胜利者ID
}

func (x *Result_Notify) Reset() {
	*x = Result_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result_Notify) ProtoMessage() {}

func (x *Result_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result_Notify.ProtoReflect.Descriptor instead.
func (*Result_Notify) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{12}
}

func (x *Result_Notify) GetWinnerID() uint64 {
	if x != nil {
		return x.WinnerID
	}
	return 0
}

// 准备
type Ready_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ready_Request) Reset() {
	*x = Ready_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ready_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready_Request) ProtoMessage() {}

func (x *Ready_Request) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready_Request.ProtoReflect.Descriptor instead.
func (*Ready_Request) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{13}
}

type Ready_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorInfo `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Ready_Response) Reset() {
	*x = Ready_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ready_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready_Response) ProtoMessage() {}

func (x *Ready_Response) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready_Response.ProtoReflect.Descriptor instead.
func (*Ready_Response) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{14}
}

func (x *Ready_Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// 服务端通知
// 加入房间
type JoinRoom_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *RoomInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *JoinRoom_Notify) Reset() {
	*x = JoinRoom_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoom_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom_Notify) ProtoMessage() {}

func (x *JoinRoom_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom_Notify.ProtoReflect.Descriptor instead.
func (*JoinRoom_Notify) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{15}
}

func (x *JoinRoom_Notify) GetData() *RoomInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 开始游戏消息
type Start_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start_Notify) Reset() {
	*x = Start_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start_Notify) ProtoMessage() {}

func (x *Start_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start_Notify.ProtoReflect.Descriptor instead.
func (*Start_Notify) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{16}
}

// 帧存储操作输入
type InputData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid        *uint32  `protobuf:"varint,1,opt,name=sid,proto3,oneof" json:"sid,omitempty"` //操作id
	X          *float32 `protobuf:"fixed32,2,opt,name=x,proto3,oneof" json:"x,omitempty"`    //操作位置x
	Y          *float32 `protobuf:"fixed32,3,opt,name=y,proto3,oneof" json:"y,omitempty"`    //操作位置y
	Z          *float32 `protobuf:"fixed32,5,opt,name=z,proto3,oneof" json:"z,omitempty"`
	Ex         *float32 `protobuf:"fixed32,6,opt,name=ex,proto3,oneof" json:"ex,omitempty"`
	Ey         *float32 `protobuf:"fixed32,7,opt,name=ey,proto3,oneof" json:"ey,omitempty"`
	Ez         *float32 `protobuf:"fixed32,8,opt,name=ez,proto3,oneof" json:"ez,omitempty"`
	TurretY    *float32 `protobuf:"fixed32,9,opt,name=turretY,proto3,oneof" json:"turretY,omitempty"`
	GunX       *float32 `protobuf:"fixed32,10,opt,name=gunX,proto3,oneof" json:"gunX,omitempty"`
	Hp         *uint64  `protobuf:"varint,12,opt,name=hp,proto3,oneof" json:"hp,omitempty"`                 // 血量
	Damage     *uint64  `protobuf:"varint,13,opt,name=damage,proto3,oneof" json:"damage,omitempty"`         // 伤害
	PlayerID   *uint64  `protobuf:"varint,21,opt,name=playerID,proto3,oneof" json:"playerID,omitempty"`     // 玩家id
	RoomSeatId *uint32  `protobuf:"varint,22,opt,name=roomSeatId,proto3,oneof" json:"roomSeatId,omitempty"` //操作者的位置索引id(1~N)
}

func (x *InputData) Reset() {
	*x = InputData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputData.ProtoReflect.Descriptor instead.
func (*InputData) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{17}
}

func (x *InputData) GetSid() uint32 {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return 0
}

func (x *InputData) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *InputData) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *InputData) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *InputData) GetEx() float32 {
	if x != nil && x.Ex != nil {
		return *x.Ex
	}
	return 0
}

func (x *InputData) GetEy() float32 {
	if x != nil && x.Ey != nil {
		return *x.Ey
	}
	return 0
}

func (x *InputData) GetEz() float32 {
	if x != nil && x.Ez != nil {
		return *x.Ez
	}
	return 0
}

func (x *InputData) GetTurretY() float32 {
	if x != nil && x.TurretY != nil {
		return *x.TurretY
	}
	return 0
}

func (x *InputData) GetGunX() float32 {
	if x != nil && x.GunX != nil {
		return *x.GunX
	}
	return 0
}

func (x *InputData) GetHp() uint64 {
	if x != nil && x.Hp != nil {
		return *x.Hp
	}
	return 0
}

func (x *InputData) GetDamage() uint64 {
	if x != nil && x.Damage != nil {
		return *x.Damage
	}
	return 0
}

func (x *InputData) GetPlayerID() uint64 {
	if x != nil && x.PlayerID != nil {
		return *x.PlayerID
	}
	return 0
}

func (x *InputData) GetRoomSeatId() uint32 {
	if x != nil && x.RoomSeatId != nil {
		return *x.RoomSeatId
	}
	return 0
}

// 帧数据
type FrameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameID *uint32      `protobuf:"varint,1,opt,name=frameID,proto3,oneof" json:"frameID,omitempty"` // 帧ID
	Input   []*InputData `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`            // 操作输入
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{18}
}

func (x *FrameData) GetFrameID() uint32 {
	if x != nil && x.FrameID != nil {
		return *x.FrameID
	}
	return 0
}

func (x *FrameData) GetInput() []*InputData {
	if x != nil {
		return x.Input
	}
	return nil
}

// 广播帧消息
type FrameMsg_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frames []*FrameData `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"` // 帧数据
}

func (x *FrameMsg_Notify) Reset() {
	*x = FrameMsg_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameMsg_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMsg_Notify) ProtoMessage() {}

func (x *FrameMsg_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMsg_Notify.ProtoReflect.Descriptor instead.
func (*FrameMsg_Notify) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{19}
}

func (x *FrameMsg_Notify) GetFrames() []*FrameData {
	if x != nil {
		return x.Frames
	}
	return nil
}

// 结果消息
type Win_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerID uint64 `protobuf:"varint,1,opt,name=winnerID,proto3" json:"winnerID,omitempty"` // 胜利者ID
}

func (x *Win_Notify) Reset() {
	*x = Win_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tank_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Win_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Win_Notify) ProtoMessage() {}

func (x *Win_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_tank_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Win_Notify.ProtoReflect.Descriptor instead.
func (*Win_Notify) Descriptor() ([]byte, []int) {
	return file_tank_proto_rawDescGZIP(), []int{20}
}

func (x *Win_Notify) GetWinnerID() uint64 {
	if x != nil {
		return x.WinnerID
	}
	return 0
}

var File_tank_proto protoreflect.FileDescriptor

var file_tank_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x31, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x38, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8a, 0x01,
	0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65,
	0x65, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x35, 0x0a,
	0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x54, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x25,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b,
	0x0a, 0x11, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x12, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x88, 0x03, 0x0a, 0x0c, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1d, 0x0a, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x03, 0x73, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02, 0x52, 0x01, 0x78, 0x88, 0x01, 0x01,
	0x12, 0x11, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x03, 0x52, 0x01, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x04,
	0x52, 0x01, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x05, 0x52, 0x02, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x48, 0x06, 0x52, 0x02, 0x65, 0x79, 0x88, 0x01, 0x01,
	0x12, 0x13, 0x0a, 0x02, 0x65, 0x7a, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x48, 0x07, 0x52, 0x02,
	0x65, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x59,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x48, 0x08, 0x52, 0x07, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74,
	0x59, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x67, 0x75, 0x6e, 0x58, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x09, 0x52, 0x04, 0x67, 0x75, 0x6e, 0x58, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a,
	0x02, 0x68, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x48, 0x0a, 0x52, 0x02, 0x68, 0x70, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x0b, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x73, 0x69, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x78, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x79, 0x42,
	0x04, 0x0a, 0x02, 0x5f, 0x7a, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x78, 0x42, 0x05, 0x0a, 0x03,
	0x5f, 0x65, 0x79, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x7a, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x74,
	0x75, 0x72, 0x72, 0x65, 0x74, 0x59, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x67, 0x75, 0x6e, 0x58, 0x42,
	0x05, 0x0a, 0x03, 0x5f, 0x68, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x22, 0x2b, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x0f,
	0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x35, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x33, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0xbc, 0x03, 0x0a, 0x09,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x03, 0x73, 0x69, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x11, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x01, 0x78,
	0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02,
	0x52, 0x01, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x48, 0x03, 0x52, 0x01, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65, 0x78, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x48, 0x04, 0x52, 0x02, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x13,
	0x0a, 0x02, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x48, 0x05, 0x52, 0x02, 0x65, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x65, 0x7a, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x06, 0x52, 0x02, 0x65, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x74, 0x75, 0x72, 0x72,
	0x65, 0x74, 0x59, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x48, 0x07, 0x52, 0x07, 0x74, 0x75, 0x72,
	0x72, 0x65, 0x74, 0x59, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x67, 0x75, 0x6e, 0x58, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x02, 0x48, 0x08, 0x52, 0x04, 0x67, 0x75, 0x6e, 0x58, 0x88, 0x01, 0x01,
	0x12, 0x13, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x48, 0x09, 0x52, 0x02,
	0x68, 0x70, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x04, 0x48, 0x0a, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x04, 0x48, 0x0b, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44,
	0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x61, 0x74, 0x49,
	0x64, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x0c, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x53,
	0x65, 0x61, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x73, 0x69, 0x64,
	0x42, 0x04, 0x0a, 0x02, 0x5f, 0x78, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x79, 0x42, 0x04, 0x0a, 0x02,
	0x5f, 0x7a, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x78, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x79,
	0x42, 0x05, 0x0a, 0x03, 0x5f, 0x65, 0x7a, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x75, 0x72, 0x72,
	0x65, 0x74, 0x59, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x67, 0x75, 0x6e, 0x58, 0x42, 0x05, 0x0a, 0x03,
	0x5f, 0x68, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x09, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x0f, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x4d, 0x73, 0x67, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x25, 0x0a, 0x06, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x73, 0x22, 0x28, 0x0a, 0x0a, 0x57, 0x69, 0x6e, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tank_proto_rawDescOnce sync.Once
	file_tank_proto_rawDescData = file_tank_proto_rawDesc
)

func file_tank_proto_rawDescGZIP() []byte {
	file_tank_proto_rawDescOnce.Do(func() {
		file_tank_proto_rawDescData = protoimpl.X.CompressGZIP(file_tank_proto_rawDescData)
	})
	return file_tank_proto_rawDescData
}

var file_tank_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tank_proto_goTypes = []interface{}{
	(*ErrorInfo)(nil),           // 0: pb.errorInfo
	(*UserInfo)(nil),            // 1: pb.userInfo
	(*RoomInfo)(nil),            // 2: pb.roomInfo
	(*Login_Request)(nil),       // 3: pb.Login_Request
	(*Login_Response)(nil),      // 4: pb.Login_Response
	(*CreateRoom_Request)(nil),  // 5: pb.CreateRoom_Request
	(*CreateRoom_Response)(nil), // 6: pb.CreateRoom_Response
	(*JoinRoom_Request)(nil),    // 7: pb.JoinRoom_Request
	(*JoinRoom_Response)(nil),   // 8: pb.JoinRoom_Response
	(*LeaveRoom_Request)(nil),   // 9: pb.LeaveRoom_Request
	(*LeaveRoom_Response)(nil),  // 10: pb.LeaveRoom_Response
	(*Input_Notify)(nil),        // 11: pb.Input_Notify
	(*Result_Notify)(nil),       // 12: pb.Result_Notify
	(*Ready_Request)(nil),       // 13: pb.Ready_Request
	(*Ready_Response)(nil),      // 14: pb.Ready_Response
	(*JoinRoom_Notify)(nil),     // 15: pb.JoinRoom_Notify
	(*Start_Notify)(nil),        // 16: pb.Start_Notify
	(*InputData)(nil),           // 17: pb.InputData
	(*FrameData)(nil),           // 18: pb.FrameData
	(*FrameMsg_Notify)(nil),     // 19: pb.FrameMsg_Notify
	(*Win_Notify)(nil),          // 20: pb.Win_Notify
}
var file_tank_proto_depIdxs = []int32{
	1,  // 0: pb.roomInfo.players:type_name -> pb.userInfo
	0,  // 1: pb.Login_Response.error:type_name -> pb.errorInfo
	0,  // 2: pb.CreateRoom_Response.error:type_name -> pb.errorInfo
	2,  // 3: pb.CreateRoom_Response.data:type_name -> pb.roomInfo
	0,  // 4: pb.JoinRoom_Response.error:type_name -> pb.errorInfo
	2,  // 5: pb.JoinRoom_Response.data:type_name -> pb.roomInfo
	0,  // 6: pb.LeaveRoom_Response.error:type_name -> pb.errorInfo
	0,  // 7: pb.Ready_Response.error:type_name -> pb.errorInfo
	2,  // 8: pb.JoinRoom_Notify.data:type_name -> pb.roomInfo
	17, // 9: pb.FrameData.input:type_name -> pb.InputData
	18, // 10: pb.FrameMsg_Notify.frames:type_name -> pb.FrameData
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_tank_proto_init() }
func file_tank_proto_init() {
	if File_tank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoom_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoom_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoom_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoom_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoom_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoom_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ready_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ready_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoom_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameMsg_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tank_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Win_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tank_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_tank_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_tank_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_tank_proto_msgTypes[17].OneofWrappers = []interface{}{}
	file_tank_proto_msgTypes[18].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tank_proto_goTypes,
		DependencyIndexes: file_tank_proto_depIdxs,
		MessageInfos:      file_tank_proto_msgTypes,
	}.Build()
	File_tank_proto = out.File
	file_tank_proto_rawDesc = nil
	file_tank_proto_goTypes = nil
	file_tank_proto_depIdxs = nil
}
